global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    env: development
    app: egofi

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  # In dev, backend runs on host machine
  - job_name: egofi_backend
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:3000"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "local"
